//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class emprunt
    {
        public int idEmprunt { get; set; }
        public int idUser { get; set; }
        public int idOuvrage { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual ouvrage ouvrage { get; set; }
        public virtual user user { get; set; }
    }
}
