//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class ouvrage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ouvrage()
        {
            this.emprunts = new HashSet<emprunt>();
        }
    
        public int idOuvrage { get; set; }
        public string titre { get; set; }
        public string auteur { get; set; }
        public string theme { get; set; }
        public int nbrExemplaire { get; set; }
        public int nbrExemplaireNonEmp { get; set; }
        public int description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emprunt> emprunts { get; set; }
    }
}
